/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as MypageRouteImport } from './routes/mypage'
import { Route as NotesRouteRouteImport } from './routes/notes.route'
import { Route as ExercisesRouteRouteImport } from './routes/exercises.route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExercisesIndexRouteImport } from './routes/exercises.index'
import { Route as NotesNoteIdRouteImport } from './routes/notes.$noteId'
import { Route as ExercisesNewRouteImport } from './routes/exercises.new'
import { Route as ExercisesExerciseIdRouteImport } from './routes/exercises.$exerciseId'
import { Route as NotesTodayIndexRouteImport } from './routes/notes.today.index'
import { Route as NotesTodayFormRouteImport } from './routes/notes.today._form'
import { Route as NotesTodayFormMetaRouteImport } from './routes/notes.today._form.meta'
import { Route as NotesTodayFormAddExerciseRouteImport } from './routes/notes.today._form.add-exercise'

const NotesTodayRouteImport = createFileRoute('/notes/today')()

const MypageRoute = MypageRouteImport.update({
  id: '/mypage',
  path: '/mypage',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRouteRoute = NotesRouteRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesRouteRoute = ExercisesRouteRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesTodayRoute = NotesTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => NotesRouteRoute,
} as any)
const ExercisesIndexRoute = ExercisesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExercisesRouteRoute,
} as any)
const NotesNoteIdRoute = NotesNoteIdRouteImport.update({
  id: '/$noteId',
  path: '/$noteId',
  getParentRoute: () => NotesRouteRoute,
} as any)
const ExercisesNewRoute = ExercisesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ExercisesRouteRoute,
} as any)
const ExercisesExerciseIdRoute = ExercisesExerciseIdRouteImport.update({
  id: '/$exerciseId',
  path: '/$exerciseId',
  getParentRoute: () => ExercisesRouteRoute,
} as any)
const NotesTodayIndexRoute = NotesTodayIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NotesTodayRoute,
} as any)
const NotesTodayFormRoute = NotesTodayFormRouteImport.update({
  id: '/_form',
  getParentRoute: () => NotesTodayRoute,
} as any)
const NotesTodayFormMetaRoute = NotesTodayFormMetaRouteImport.update({
  id: '/meta',
  path: '/meta',
  getParentRoute: () => NotesTodayFormRoute,
} as any)
const NotesTodayFormAddExerciseRoute =
  NotesTodayFormAddExerciseRouteImport.update({
    id: '/add-exercise',
    path: '/add-exercise',
    getParentRoute: () => NotesTodayFormRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exercises': typeof ExercisesRouteRouteWithChildren
  '/notes': typeof NotesRouteRouteWithChildren
  '/mypage': typeof MypageRoute
  '/exercises/$exerciseId': typeof ExercisesExerciseIdRoute
  '/exercises/new': typeof ExercisesNewRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/exercises/': typeof ExercisesIndexRoute
  '/notes/today': typeof NotesTodayFormRouteWithChildren
  '/notes/today/': typeof NotesTodayIndexRoute
  '/notes/today/add-exercise': typeof NotesTodayFormAddExerciseRoute
  '/notes/today/meta': typeof NotesTodayFormMetaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/notes': typeof NotesRouteRouteWithChildren
  '/mypage': typeof MypageRoute
  '/exercises/$exerciseId': typeof ExercisesExerciseIdRoute
  '/exercises/new': typeof ExercisesNewRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/exercises': typeof ExercisesIndexRoute
  '/notes/today': typeof NotesTodayIndexRoute
  '/notes/today/add-exercise': typeof NotesTodayFormAddExerciseRoute
  '/notes/today/meta': typeof NotesTodayFormMetaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/exercises': typeof ExercisesRouteRouteWithChildren
  '/notes': typeof NotesRouteRouteWithChildren
  '/mypage': typeof MypageRoute
  '/exercises/$exerciseId': typeof ExercisesExerciseIdRoute
  '/exercises/new': typeof ExercisesNewRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/exercises/': typeof ExercisesIndexRoute
  '/notes/today': typeof NotesTodayRouteWithChildren
  '/notes/today/_form': typeof NotesTodayFormRouteWithChildren
  '/notes/today/': typeof NotesTodayIndexRoute
  '/notes/today/_form/add-exercise': typeof NotesTodayFormAddExerciseRoute
  '/notes/today/_form/meta': typeof NotesTodayFormMetaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/exercises'
    | '/notes'
    | '/mypage'
    | '/exercises/$exerciseId'
    | '/exercises/new'
    | '/notes/$noteId'
    | '/exercises/'
    | '/notes/today'
    | '/notes/today/'
    | '/notes/today/add-exercise'
    | '/notes/today/meta'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/notes'
    | '/mypage'
    | '/exercises/$exerciseId'
    | '/exercises/new'
    | '/notes/$noteId'
    | '/exercises'
    | '/notes/today'
    | '/notes/today/add-exercise'
    | '/notes/today/meta'
  id:
    | '__root__'
    | '/'
    | '/exercises'
    | '/notes'
    | '/mypage'
    | '/exercises/$exerciseId'
    | '/exercises/new'
    | '/notes/$noteId'
    | '/exercises/'
    | '/notes/today'
    | '/notes/today/_form'
    | '/notes/today/'
    | '/notes/today/_form/add-exercise'
    | '/notes/today/_form/meta'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExercisesRouteRoute: typeof ExercisesRouteRouteWithChildren
  NotesRouteRoute: typeof NotesRouteRouteWithChildren
  MypageRoute: typeof MypageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mypage': {
      id: '/mypage'
      path: '/mypage'
      fullPath: '/mypage'
      preLoaderRoute: typeof MypageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises': {
      id: '/exercises'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof ExercisesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/today': {
      id: '/notes/today'
      path: '/today'
      fullPath: '/notes/today'
      preLoaderRoute: typeof NotesTodayRouteImport
      parentRoute: typeof NotesRouteRoute
    }
    '/exercises/': {
      id: '/exercises/'
      path: '/'
      fullPath: '/exercises/'
      preLoaderRoute: typeof ExercisesIndexRouteImport
      parentRoute: typeof ExercisesRouteRoute
    }
    '/notes/$noteId': {
      id: '/notes/$noteId'
      path: '/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof NotesNoteIdRouteImport
      parentRoute: typeof NotesRouteRoute
    }
    '/exercises/new': {
      id: '/exercises/new'
      path: '/new'
      fullPath: '/exercises/new'
      preLoaderRoute: typeof ExercisesNewRouteImport
      parentRoute: typeof ExercisesRouteRoute
    }
    '/exercises/$exerciseId': {
      id: '/exercises/$exerciseId'
      path: '/$exerciseId'
      fullPath: '/exercises/$exerciseId'
      preLoaderRoute: typeof ExercisesExerciseIdRouteImport
      parentRoute: typeof ExercisesRouteRoute
    }
    '/notes/today/': {
      id: '/notes/today/'
      path: '/'
      fullPath: '/notes/today/'
      preLoaderRoute: typeof NotesTodayIndexRouteImport
      parentRoute: typeof NotesTodayRoute
    }
    '/notes/today/_form': {
      id: '/notes/today/_form'
      path: '/today'
      fullPath: '/notes/today'
      preLoaderRoute: typeof NotesTodayFormRouteImport
      parentRoute: typeof NotesTodayRoute
    }
    '/notes/today/_form/meta': {
      id: '/notes/today/_form/meta'
      path: '/meta'
      fullPath: '/notes/today/meta'
      preLoaderRoute: typeof NotesTodayFormMetaRouteImport
      parentRoute: typeof NotesTodayFormRoute
    }
    '/notes/today/_form/add-exercise': {
      id: '/notes/today/_form/add-exercise'
      path: '/add-exercise'
      fullPath: '/notes/today/add-exercise'
      preLoaderRoute: typeof NotesTodayFormAddExerciseRouteImport
      parentRoute: typeof NotesTodayFormRoute
    }
  }
}

interface ExercisesRouteRouteChildren {
  ExercisesExerciseIdRoute: typeof ExercisesExerciseIdRoute
  ExercisesNewRoute: typeof ExercisesNewRoute
  ExercisesIndexRoute: typeof ExercisesIndexRoute
}

const ExercisesRouteRouteChildren: ExercisesRouteRouteChildren = {
  ExercisesExerciseIdRoute: ExercisesExerciseIdRoute,
  ExercisesNewRoute: ExercisesNewRoute,
  ExercisesIndexRoute: ExercisesIndexRoute,
}

const ExercisesRouteRouteWithChildren = ExercisesRouteRoute._addFileChildren(
  ExercisesRouteRouteChildren,
)

interface NotesTodayFormRouteChildren {
  NotesTodayFormAddExerciseRoute: typeof NotesTodayFormAddExerciseRoute
  NotesTodayFormMetaRoute: typeof NotesTodayFormMetaRoute
}

const NotesTodayFormRouteChildren: NotesTodayFormRouteChildren = {
  NotesTodayFormAddExerciseRoute: NotesTodayFormAddExerciseRoute,
  NotesTodayFormMetaRoute: NotesTodayFormMetaRoute,
}

const NotesTodayFormRouteWithChildren = NotesTodayFormRoute._addFileChildren(
  NotesTodayFormRouteChildren,
)

interface NotesTodayRouteChildren {
  NotesTodayFormRoute: typeof NotesTodayFormRouteWithChildren
  NotesTodayIndexRoute: typeof NotesTodayIndexRoute
}

const NotesTodayRouteChildren: NotesTodayRouteChildren = {
  NotesTodayFormRoute: NotesTodayFormRouteWithChildren,
  NotesTodayIndexRoute: NotesTodayIndexRoute,
}

const NotesTodayRouteWithChildren = NotesTodayRoute._addFileChildren(
  NotesTodayRouteChildren,
)

interface NotesRouteRouteChildren {
  NotesNoteIdRoute: typeof NotesNoteIdRoute
  NotesTodayRoute: typeof NotesTodayRouteWithChildren
}

const NotesRouteRouteChildren: NotesRouteRouteChildren = {
  NotesNoteIdRoute: NotesNoteIdRoute,
  NotesTodayRoute: NotesTodayRouteWithChildren,
}

const NotesRouteRouteWithChildren = NotesRouteRoute._addFileChildren(
  NotesRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExercisesRouteRoute: ExercisesRouteRouteWithChildren,
  NotesRouteRoute: NotesRouteRouteWithChildren,
  MypageRoute: MypageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
